[package]
name = "extract-firmware-nouveau"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.23", features = ["derive", "string"] }
flate2 = { version = "1.0.35" }
itertools = "0.14.0"
regex = "1.11.1"
tempfile = "3.16.0"